### ISSUE TITLE
Keep PyPI up to date

### ISSUE THREAD

**Issue by m1ghtym0** [angr/archr#30]
@zardus Can you add me to the PyPI project, I'd like to keep this up to date.
Thanks!

**Comment by rhelmot** [comment]
will there ever be angr features which archr depends on? if so then we should just add this to the standard angr package release process.

**Comment by m1ghtym0** [comment]
Not sure, ofc there is an angr bow, but other than that archr should be pretty independent of angr.
Not sure if @zardus has something in mind in this direction?

**Comment by zardus** [comment]
I added you in there!

I think the idea is to make archr usable without angr (i.e., have angr as
an optional dependency), but having it as part of the angr release process
would make sense to me anyways.

- Yan

**Comment by twizmwazin** [comment]
archr has been released for a while now along with angr.
