### ISSUE TITLE
Target injection does a recursive chown on /

### ISSUE THREAD

**Issue by ConnorNelson** [angr/archr#34]
When a bow injects some artifact into the target (e.g. strace), and the target's user is not root, it ends up doing a recursive chown on `/`.

This seems unnecessarily aggressive. It should probably recursively chown `/tmp`.

**Comment by zardus** [comment]
big lol

**Comment by ConnorNelson** [comment]
See 3163f6e3448f91dd4f42fe8ae48f6ffadbc638f5
