### ISSUE TITLE
Unable to dynamically infer tcp/udp ports for running DockerTargets

### ISSUE THREAD

**Issue by twizmwazin** [angr/archr#35]
Implemented [here](https://github.com/angr/archr/blob/master/archr/targets/docker_target.py#L183), all tcp_ports and udp_ports do is read from docker inspect. While this works when we fully control the docker file, it would be worthwhile for when we don't necessarily control the docker file, or if there is a program which dynamically opens ports.

**Comment by ConnorNelson** [comment]
I was thinking a little bit about this.

We can read out the contents of `/proc/net/tcp`.

```sh
root@51aa701fdb0a:/# nc -lp 4242
```

```sh
root@51aa701fdb0a:/# cat /proc/net/tcp
  sl  local_address rem_address   st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode
   0: 00000000:1092 00000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 1395209 1 0000000000000000 100 0 0 10 0
```

That `1092` is `0x1092` = `4242`.

We can even hit this file straight from the host with:
```sh
$ cat /proc/$(docker inspect --format '{{.State.Pid}}' 51aa)/net/tcp
  sl  local_address rem_address   st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode                                                     
   0: 00000000:1092 00000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 1395209 1 0000000000000000 100 0 0 10 0                   
```

We can parse out that file to understand what ports are open at a given point in time.
