### ISSUE TITLE
Temporary directories cleanup seems to not be working in some cases

### ISSUE THREAD

**Issue by dnivra** [angr/archr#83]
I find that the temporary directories created by some analyzers are still around even after the entire script has exited. One case I found this is for `angrProjectAnalyzer`. Is it because `angrProjectAnalyzer` does not implement context management interface functions(eg: `__enter__`, `__exit__` etc)?

**Comment by ltfish** [comment]
Which directories?

**Comment by Kyle-Kyle** [comment]
the one in `angrProjectAnalyzer` is left as a file leak intentionally according to its comment. I don't know why though

**Comment by dnivra** [comment]
Yes it's the one Kyle mentioned: https://github.com/angr/archr/blob/master/archr/analyzers/angr_project.py#L82. I noticed the comment only now; seems like it's a known issue.
