### ISSUE TITLE
QEMUTracerAnalyzer fails to set taint_fd when emulating CGC binaries

### ISSUE THREAD

**Issue by dnivra** [angr/archr#88]
QEMUTracerAnalyzer complains that it was unable to find the last read marker and so cannot set taint_fd when emulating CGC binaries(https://github.com/angr/archr/blob/master/archr/analyzers/qemu_tracer.py#L176). Kyle said this check is part of a bigger feature that was not implemented in and not required for CGC qemu. Perhaps the check should be modified to be triggered only for targets where it is relevant. It is fairly straightforward to reproduce this: emulate any CGC binary with bytes from a PoV as input. I can provide a script to reproduce if needed.

**Comment by Kyle-Kyle** [comment]
fixed with commit https://github.com/angr/archr/commit/159a430d5acf5505617ac6a6af754fd38060e7b9
