### ISSUE TITLE
QEMUTracerAnalyzer crashes with BrokenPipeError before entire input can be written to stdin of CGC binary

### ISSUE THREAD

**Issue by dnivra** [angr/archr#90]
When attempting to generate a trace of a CGC binary using a PoV as input, the QEMUTracer crashes with BrokenPipeError. I debugged the issue a bit and found that the error occurs when the SendAction is being run(second action run by loop at https://github.com/angr/archr/blob/master/archr/targets/flight.py#L97). The size of the input PoV is about 1.7MB and I think the entire input is not transmitted in one send but is broken up into multiple chunks. However, the channel seems to have been closed by the time second chunk is written. [This ZIP file](https://github.com/angr/archr/files/6525539/archr-issue-90.zip) has the binary, input and script needed to reproduce this crash.

**Comment by rhelmot** [comment]
I believe you can safely discard this sample. I went through the trouble of pulling up the official cgc vm with the official cgc pov replay tooling, and it does not replay correctly even there:

```
# service - NRFIN_00039-POV_00000.xml
# connected to ('127.226.44.33', 13492)
ok 1 - write: sent 9 bytes
ok 2 - write: sent 8 bytes
ok 3 - write: sent 32754 bytes
ok 4 - write: sent 32768 bytes
ok 5 - write: sent 32753 bytes
ok 6 - write: sent 32768 bytes
ok 7 - write: sent 32753 bytes
ok 8 - write: sent 32768 bytes
ok 9 - write: sent 32753 bytes
not ok 10 - recv failed
# stopping due to failure
# tests passed: 9
# tests failed: 1
# total tests passed: 9
# total tests failed: 1
# polls passed: 0
# polls failed: 1
# core identified
# process cored.  (signal 11: SIGSEGV)
vagrant@crs:/vagrant$
```

It sends a bit more data before dying, but I'm willing to bet that's just because they're using a tcp socket instead of a pipe for IPC so the buffering characteristics are different.

**Comment by dnivra** [comment]
Ah I see. Yeah if it doesn't work correctly on official setup, I guess it's safe to ignore this and close the issue. Thanks a lot for looking into this and testing it out!
