### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by ConnorNelson** [angr/archr#92]
Networking for docker containers on MacOS is bad. We either need to perform networking via another container on the same network as the target container, or forward ports to the host.

**Comment by ConnorNelson** [comment]
We need to make shellphish_qemu optional, since MacOS cannot install it.

**Comment by ConnorNelson** [comment]
Exposing to the host is an issue, because the socket becomes unusable if we connect before the port is available, with no way to detect the failure.

**Comment by twizmwazin** [comment]
Can you elaborate on what the issue with docker networking on macos is?

**Comment by ConnorNelson** [comment]
By default, when you start up a docker container, it gets its own network namespace and is assigned it's own IP address. MacOS's docker implementation does not allow you to talk to this IP address. As far as I can tell, the only options are to either forward the port from the host, or to create another container in the same network namespace / network and communicate via that container. 

Unfortunately, forwarding the port from the host seems to create a really strange issue where socket connections don't fail to connect when the port isn't yet being bound by the host. This results in a socket that python lets you send data to without complaint, and receives an empty string back (both without any exceptions). However, archr relies on exceptions when connecting to continuously retry connections until the service is back up.
